apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque
data:
  LARAVEL_DATABASE_NAME: "d2Vla2x5"
  LARAVEL_DATABASE_USER: "cmFsb25zbw=="
  LARAVEL_DATABASE_PASSWORD: "MTIzNA=="
